export const MOCK_DELTAS: Record<string, Record<string, number>> = {
  zomato: {
    financial_health: +8,
    profitability: +12,
    growth: +5,
    valuation: -3,
    technical: +2,
    performance: -1,
    institutional_signals: +4,
    management_governance: 0,
    business_quality: +4,
    capital_discipline: -1,
    earnings_quality: +7,
    execution_quality: +3,
    risk: -2,
  },
  axisbank: {
    financial_health: +3,
    profitability: +1,
    growth: -4,
    valuation: +6,
    technical: -8,
    performance: +2,
    institutional_signals: -1,
    management_governance: +5,
    business_quality: +2,
    capital_discipline: +1,
    earnings_quality: -3,
    execution_quality: 0,
    risk: +4,
  },
  tcs: {
    financial_health: +1,
    profitability: 0,
    growth: -2,
    valuation: +3,
    technical: -5,
    performance: -3,
    institutional_signals: +2,
    management_governance: +1,
    business_quality: 0,
    capital_discipline: +2,
    earnings_quality: +1,
    execution_quality: -1,
    risk: 0,
  },
}
