/**
 * V2 Verdict Data — Quant + Qual + Risk Architecture
 *
 * Mock data for 3 demo stocks with full pillar structures.
 * Each stock has base pillar/segment/signal data; profile-specific
 * verdicts are generated by applying profile weights.
 *
 * Stocks: Zomato (Eternal), Axis Bank, TCS
 */

import type {
  StockVerdictV2,
  PillarVerdict,
  SegmentVerdictV2,
  QualSignal,
  NewsEvent,
  ConfidenceIndicator,
} from '@/types'
import { getScoreBandEnum } from '@/lib/scoring'
import { getOverallVerdict } from '@/lib/scoring'

// ============================================================
// HELPER: Build signal groups from scored signals
// ============================================================

function buildSignal(
  id: string, name: string, group: string,
  escalationTier: 'hard' | 'soft' | 'score_only',
  score: number,
  state: QualSignal['state'],
  userText: string,
  isTriggered = false,
): QualSignal {
  return { id, name, group, escalationTier, score, state, userText, isTriggered, version: 'v1' }
}

function buildConfidence(computed: number, total: number): ConfidenceIndicator {
  return {
    signalsComputed: computed,
    signalsTotal: total,
    state: computed === total ? 'full' : computed >= total * 0.7 ? 'partial' : 'limited_history',
    tooltip: `Based on ${computed} of ${total} signals`,
    dataRange: 'FY20–FY24',
  }
}

// ============================================================
// ZOMATO (ETERNAL) — New Economy / Food Tech
// ============================================================

const zomatoQuantSegments: SegmentVerdictV2[] = [
  {
    id: 'profitability', name: 'Profitability', pillar: 'quant', scoringType: 'scored',
    score: 42, scoreBand: 'mixed', weight: 20,
    status: 'neutral',
    interpretation: 'First profitable quarter achieved but margins still thin. ROE is low at 4% vs sector avg 12%.',
    quickInsight: 'Just turned profitable — early innings',
    scoreJustification: 'Scored 42/100: First-time profitability is positive, but margins are industry-low and sustainability is unproven.',
    metrics: [],
  },
  {
    id: 'growth', name: 'Growth', pillar: 'quant', scoringType: 'scored',
    score: 92, scoreBand: 'strong', weight: 25,
    status: 'positive',
    interpretation: 'Revenue CAGR of 70%+ driven by Blinkit quick commerce. TAM runway remains massive.',
    quickInsight: 'Hypergrowth — 70%+ revenue CAGR',
    scoreJustification: 'Scored 92/100: Exceptional growth across food delivery and quick commerce. One of the fastest-growing large-caps in India.',
    metrics: [],
  },
  {
    id: 'valuation', name: 'Valuation', pillar: 'quant', scoringType: 'scored',
    score: 35, scoreBand: 'weak', weight: 20,
    status: 'negative',
    interpretation: 'P/S ratio of 12x vs sector average 6x. Premium pricing assumes sustained hypergrowth.',
    quickInsight: 'Expensive — priced for perfection',
    scoreJustification: 'Scored 35/100: Premium valuation leaves little margin for error. Justified only if growth sustains 50%+ for 3+ years.',
    metrics: [],
  },
  {
    id: 'financial_health', name: 'Financial Health', pillar: 'quant', scoringType: 'scored',
    score: 58, scoreBand: 'mixed', weight: 25,
    status: 'neutral',
    interpretation: 'Cash-rich balance sheet from IPO proceeds. But operating cash flow just turned positive.',
    quickInsight: 'Strong cash position, weak operating cash flow',
    scoreJustification: 'Scored 58/100: Net cash positive but OCF is nascent. Financial health depends on sustained profitability.',
    metrics: [],
  },
  {
    id: 'technical', name: 'Technical Indicators', pillar: 'quant', scoringType: 'scored',
    score: 75, scoreBand: 'good', weight: 10,
    status: 'positive',
    interpretation: 'Strong uptrend with price above 50 & 200 DMA. RSI at 62 — bullish but not overbought.',
    quickInsight: 'Bullish trend intact',
    metrics: [],
  },
  {
    id: 'performance', name: 'Performance', pillar: 'quant', scoringType: 'context',
    status: 'positive',
    interpretation: '1Y return of 120%+, significantly outperforming Nifty. High trading volumes confirm institutional interest.',
    quickInsight: '120% return in 1 year',
    metrics: [],
  },
  {
    id: 'institutional_signals', name: 'Institutional / Market Signals', pillar: 'quant', scoringType: 'context',
    status: 'positive',
    interpretation: 'FII holding increased from 35% to 42% in last 4 quarters. 18 of 22 analysts rate BUY.',
    quickInsight: 'Strong FII buying + analyst consensus BUY',
    metrics: [],
  },
]

const zomatoQualFactors: SegmentVerdictV2[] = [
  {
    id: 'management_governance', name: 'Management & Governance', pillar: 'qual',
    scoringType: 'scored', score: 68, scoreBand: 'good', label: 'ADEQUATE', weight: 20,
    status: 'positive',
    interpretation: 'Deepinder Goyal holds significant stake and has been increasing. Clean governance with independent board. New-age company governance is above average.',
    confidenceIndicator: buildConfidence(12, 15),
    signalGroups: [
      {
        id: 'A', name: 'Promoter Alignment', role: 'anchor', score: 72,
        signals: [
          buildSignal('A1', 'Promoter Skin in the Game', 'A', 'hard', 78, 'strong', 'Deepinder Goyal holds 4.5% directly and has been increasing stake through open market purchases — strong alignment.'),
          buildSignal('A2', 'Holding Trend (3Y)', 'A', 'score_only', 70, 'strong', 'Promoter holding has increased from 3.8% to 4.5% over 3 years — buying, not selling.'),
          buildSignal('A3', 'Pledge Status', 'A', 'soft', 90, 'strong', 'Zero promoter shares pledged — clean ownership structure.'),
          buildSignal('A4', 'Insider Transactions', 'A', 'score_only', 65, 'strong', 'Recent ESOP exercises by senior management at current levels signal confidence.'),
          buildSignal('A5', 'Related Party Transactions', 'A', 'soft', 55, 'monitor', 'Some related party transactions with Blinkit (now wholly-owned subsidiary) — disclosed but worth monitoring scale.'),
        ],
      },
      {
        id: 'B', name: 'Governance Structure', role: 'scored', weight: 0.50, score: 65,
        signals: [
          buildSignal('B1', 'Auditor Quality & Tenure', 'B', 'hard', 85, 'strong', 'Deloitte as auditor — top-tier independent oversight with appropriate rotation.'),
          buildSignal('B2', 'Board Independence', 'B', 'score_only', 70, 'strong', 'Board has 60% independent directors including experienced professionals from diverse backgrounds.'),
          buildSignal('B3', 'Regulatory Compliance', 'B', 'hard', 80, 'strong', 'Clean regulatory track record — no SEBI actions or material penalties.'),
          buildSignal('B4', 'Compensation Alignment', 'B', 'score_only', 45, 'monitor', 'Heavy ESOP-based compensation — aligns with growth but dilutes existing shareholders.'),
          buildSignal('B5', 'Disclosure Quality', 'B', 'score_only', 55, 'monitor', 'Adequate disclosures for a new-age company. Concall quality is good but segment reporting could be more granular.'),
          buildSignal('B6', 'Whistleblower / Ethics', 'B', 'score_only', 50, 'monitor', 'Basic ethics framework in place. As a young company, governance maturity is still evolving.'),
        ],
      },
      {
        id: 'C', name: 'Management Capability', role: 'scored', weight: 0.50, score: 68,
        signals: [
          buildSignal('C1', 'Capital Allocation Track Record', 'C', 'score_only', 72, 'strong', 'Blinkit acquisition proving to be a masterstroke. Hyperpure and other bets are more questionable but smaller.'),
          buildSignal('C2', 'Execution vs Guidance', 'C', 'score_only', 65, 'strong', 'Management has consistently met or exceeded guidance on profitability timeline.'),
          buildSignal('C3', 'Strategic Clarity', 'C', 'score_only', 68, 'strong', 'Clear strategy: food delivery + quick commerce + going-out. Well-articulated roadmap for each vertical.'),
        ],
      },
    ],
  },
  {
    id: 'business_quality', name: 'Business Quality', pillar: 'qual',
    scoringType: 'scored', score: 71, scoreBand: 'good', label: 'GOOD', weight: 25,
    status: 'positive',
    interpretation: 'Strong market position with network effects. Margins improving rapidly as scale builds. Customer concentration risk is low.',
    confidenceIndicator: buildConfidence(10, 11),
    signalGroups: [
      {
        id: 'A', name: 'Margin & Return Durability', role: 'anchor', score: 62,
        signals: [
          buildSignal('A1', 'ROCE Consistency', 'A', 'score_only', 35, 'flag', 'ROCE is low at 4% — expected for a company just turning profitable but needs sustained improvement.'),
          buildSignal('A2', 'Operating Margin Stability', 'A', 'score_only', 55, 'monitor', 'Operating margins just turned positive. Too early for stability assessment.'),
          buildSignal('A3', 'Margin Expansion Trend', 'A', 'score_only', 82, 'strong', 'Rapid margin expansion from -15% to +2% in 18 months — strong operating leverage.'),
          buildSignal('A4', 'Revenue Quality', 'A', 'score_only', 75, 'strong', 'High-frequency, recurring transactions — food delivery has inherent repeat behavior.'),
          buildSignal('A5', 'Return vs Cost of Capital', 'A', 'score_only', 45, 'monitor', 'Returns are approaching cost of capital — not yet value-creating on this metric.'),
        ],
      },
      {
        id: 'B', name: 'Revenue Fragility', role: 'red_flag_only', score: 78,
        signals: [
          buildSignal('B1', 'Customer Concentration', 'B', 'soft', 90, 'strong', 'Millions of individual customers — no single customer dependency.'),
          buildSignal('B2', 'Geographic Concentration', 'B', 'soft', 60, 'monitor', 'India-only business — geographic diversification limited to domestic cities.'),
          buildSignal('B3', 'Product/Service Concentration', 'B', 'soft', 72, 'strong', 'Three distinct verticals: food delivery, quick commerce, going-out — diversifying.'),
        ],
      },
      {
        id: 'C', name: 'Pricing Power Confirmation', role: 'scored', weight: 0.50, score: 70,
        signals: [
          buildSignal('C1', 'Pricing Power Evidence', 'C', 'score_only', 70, 'strong', 'Platform take rates have increased while maintaining order growth — evidence of pricing power.'),
        ],
      },
      {
        id: 'D', name: 'Earnings Backing', role: 'scored', weight: 0.50, score: 55,
        signals: [
          buildSignal('D1', 'Cash Backing of Earnings', 'D', 'score_only', 50, 'monitor', 'Operating cash flow just turned positive — too early to assess cash backing of earnings.'),
          buildSignal('D2', 'Accrual Ratio', 'D', 'score_only', 60, 'monitor', 'Moderate accrual ratio — some portion of recent profit improvement is non-cash.'),
        ],
      },
    ],
  },
  {
    id: 'capital_discipline', name: 'Capital Discipline', pillar: 'qual',
    scoringType: 'scored', score: 55, scoreBand: 'mixed', label: 'MIXED', weight: 20,
    status: 'neutral',
    interpretation: 'Heavy ESOP dilution is the main concern. No dividends yet (understandable for growth stage). Capital deployment through Blinkit was well-timed.',
    confidenceIndicator: buildConfidence(13, 16),
    signalGroups: [
      {
        id: 'A', name: 'Dilution & Funding', role: 'scored', weight: 0.30, score: 40,
        signals: [
          buildSignal('A1', 'Equity Dilution History', 'A', 'score_only', 35, 'flag', 'Significant ESOP-driven dilution — share count has increased ~8% since IPO.'),
          buildSignal('A2', 'Debt Management', 'A', 'score_only', 85, 'strong', 'Zero debt company — funded entirely by equity and internal accruals.'),
          buildSignal('A3', 'Funding Mix', 'A', 'score_only', 30, 'flag', 'Heavily reliant on IPO cash and ESOPs — not yet self-funding from operations.'),
          buildSignal('A4', 'Working Capital Efficiency', 'A', 'score_only', 45, 'monitor', 'Negative working capital (typical for platform businesses) — efficient but thin margins mean less buffer.'),
        ],
      },
      {
        id: 'B', name: 'Capital Deployment Quality', role: 'scored', weight: 0.45, score: 65,
        signals: [
          buildSignal('B1', 'Capex ROI', 'B', 'score_only', 60, 'monitor', 'Dark store buildout is capital-intensive but showing early signs of returns. ROI timeline is 18-24 months.'),
          buildSignal('B2', 'R&D Effectiveness', 'B', 'score_only', 72, 'strong', 'Tech investments translate to operational efficiency — delivery times and costs improving.'),
          buildSignal('B3', 'Growth vs Maintenance Capex', 'B', 'score_only', 80, 'strong', 'Almost all capex is growth-oriented — new dark stores, new cities, new verticals.'),
          buildSignal('B4', 'Investment Timing', 'B', 'score_only', 70, 'strong', 'Blinkit acquisition timing was excellent — bought at distressed valuation, now a growth engine.'),
          buildSignal('B5', 'Subsidiary Health', 'B', 'score_only', 55, 'monitor', 'Blinkit is strong but Hyperpure and other bets are still loss-making.'),
          buildSignal('B6', 'Capital Allocation Consistency', 'B', 'score_only', 50, 'monitor', 'Strategy has evolved significantly — from pure food delivery to multi-vertical. Directionally right but unpredictable.'),
        ],
      },
      {
        id: 'C', name: 'Capital Returns', role: 'anchor', score: 20,
        signals: [
          buildSignal('C1', 'Dividend Track Record', 'C', 'score_only', 0, 'flag', 'No dividends — expected for a growth-stage company but zero capital returns to shareholders.'),
          buildSignal('C2', 'Buyback Discipline', 'C', 'score_only', 15, 'flag', 'No buybacks despite dilution — not returning capital even as share count increases.'),
          buildSignal('C3', 'Payout Sustainability', 'C', 'score_only', 10, 'flag', 'No payouts to assess sustainability of. FCF is barely positive.'),
          buildSignal('C4', 'Total Shareholder Return', 'C', 'score_only', 55, 'monitor', 'Returns have been strong via price appreciation, but no capital returns component.'),
        ],
      },
      {
        id: 'D', name: 'Acquisition Track Record', role: 'scored', weight: 0.25, score: 72,
        signals: [
          buildSignal('D1', 'M&A Track Record', 'D', 'score_only', 72, 'strong', 'Blinkit acquisition at ₹4,447 Cr is looking value-accretive. Other smaller bets are mixed.'),
        ],
      },
    ],
  },
  {
    id: 'earnings_quality', name: 'Earnings Quality', pillar: 'qual',
    scoringType: 'scored', score: 48, scoreBand: 'mixed', label: 'MIXED', weight: 20,
    status: 'neutral',
    interpretation: 'Earnings are nascent — just turned profitable. Cash conversion needs to improve. No reporting integrity concerns.',
    confidenceIndicator: buildConfidence(12, 14),
    signalGroups: [
      {
        id: 'A', name: 'Cash Conversion', role: 'anchor', score: 45,
        signals: [
          buildSignal('A1', 'OCF to PAT Ratio', 'A', 'score_only', 40, 'monitor', 'Operating cash flow roughly matches thin profits — ratio is adequate but scale is tiny.'),
          buildSignal('A2', 'FCF Yield', 'A', 'score_only', 35, 'flag', 'Negligible free cash flow yield — capex on dark stores absorbs most operating cash.'),
          buildSignal('A3', 'Cash Conversion Cycle', 'A', 'score_only', 60, 'monitor', 'Short cash conversion cycle due to platform model — customers pay upfront.'),
        ],
      },
      {
        id: 'B', name: 'Balance Sheet Quality', role: 'scored', weight: 0.60, score: 70,
        signals: [
          buildSignal('B1', 'Receivables Quality', 'B', 'score_only', 80, 'strong', 'Low receivables — customers pay at point of order. Restaurant payouts are timely.'),
          buildSignal('B2', 'Inventory Health', 'B', 'score_only', 65, 'strong', 'Blinkit inventory is managed efficiently with rapid turnover. No obsolescence risk.'),
          buildSignal('B3', 'Contingent Liabilities', 'B', 'soft', 70, 'strong', 'Some GST-related contingent liabilities — standard for platform companies.'),
          buildSignal('B4', 'Goodwill & Intangibles', 'B', 'score_only', 55, 'monitor', 'Significant goodwill from Blinkit acquisition — impairment risk if Blinkit underperforms.'),
          buildSignal('B5', 'Off-Balance Sheet Items', 'B', 'soft', 75, 'strong', 'Minimal off-balance sheet items — clean structure.'),
        ],
      },
      {
        id: 'C', name: 'Reporting Integrity', role: 'red_flag_only', score: 85,
        signals: [
          buildSignal('C1', 'Restatement History', 'C', 'soft', 90, 'strong', 'No financial restatements — consistent reporting since IPO.'),
          buildSignal('C2', 'Accounting Policy Changes', 'C', 'hard', 80, 'strong', 'Stable accounting policies — no changes to flatter results.'),
          buildSignal('C3', 'Auditor Opinion', 'C', 'hard', 85, 'strong', 'Clean auditor opinion from Deloitte with no qualifications.'),
        ],
      },
      {
        id: 'D', name: 'Pattern Anomalies', role: 'scored', weight: 0.40, score: 55,
        signals: [
          buildSignal('D1', 'Revenue Recognition Patterns', 'D', 'score_only', 65, 'strong', 'Revenue recognition follows a natural daily transaction pattern — no unusual spikes.'),
          buildSignal('D2', 'Expense Timing', 'D', 'score_only', 50, 'monitor', 'Some variability in marketing expense timing around festivals — explainable but notable.'),
          buildSignal('D3', 'Tax Rate Anomalies', 'D', 'score_only', 50, 'monitor', 'Low effective tax rate due to carried-forward losses — will normalize as profits grow.'),
        ],
      },
    ],
  },
  {
    id: 'execution_quality', name: 'Execution Quality', pillar: 'qual',
    scoringType: 'scored', score: 78, scoreBand: 'good', label: 'GOOD', weight: 15,
    status: 'positive',
    interpretation: 'Strong execution against stated goals. Profitability timeline was met ahead of guidance. Market share gains are consistent.',
    confidenceIndicator: buildConfidence(6, 7),
    signalGroups: [
      {
        id: 'A', name: 'Financial Delivery', role: 'anchor', score: 80,
        signals: [
          buildSignal('A1', 'Revenue Growth vs Guidance', 'A', 'score_only', 85, 'strong', 'Consistently delivers or exceeds guided revenue targets across both food delivery and Blinkit.'),
          buildSignal('A2', 'Margin Delivery vs Guidance', 'A', 'score_only', 82, 'strong', 'Profitability achieved ahead of guided timeline — management credibility is high.'),
          buildSignal('A3', 'Earnings Surprise Pattern', 'A', 'score_only', 78, 'strong', 'Positive earnings surprises in 3 of last 4 quarters — management under-promises and over-delivers.'),
          buildSignal('A4', 'Quarterly Consistency', 'A', 'score_only', 72, 'strong', 'Sequential improvement in key metrics every quarter — smooth execution trajectory.'),
        ],
      },
      {
        id: 'B', name: 'Operational Delivery', role: 'scored', weight: 1.0, score: 75,
        signals: [
          buildSignal('B1', 'Operational KPI Achievement', 'B', 'score_only', 80, 'strong', 'GOV, AOV, and order frequency all trending up — operational KPIs consistently met.'),
          buildSignal('B2', 'Market Share Trajectory', 'B', 'score_only', 70, 'strong', 'Maintaining 55%+ food delivery share while gaining quick commerce share rapidly.'),
        ],
      },
    ],
  },
]

// ============================================================
// AXIS BANK — Banking / Financial Services
// ============================================================

const axisBankQuantSegments: SegmentVerdictV2[] = [
  {
    id: 'profitability', name: 'Profitability', pillar: 'quant', scoringType: 'scored',
    score: 72, scoreBand: 'good', weight: 20,
    status: 'positive',
    interpretation: 'ROE of 16% is above sector average. NIM stable at 4.1%. Cost-to-income ratio improving.',
    quickInsight: 'Solid profitability — 16% ROE',
    metrics: [],
  },
  {
    id: 'growth', name: 'Growth', pillar: 'quant', scoringType: 'scored',
    score: 65, scoreBand: 'good', weight: 25,
    status: 'positive',
    interpretation: 'Loan book growing at 18% CAGR. Retail lending mix improving. Fee income growing 20%+.',
    quickInsight: 'Steady 18% loan growth',
    metrics: [],
  },
  {
    id: 'valuation', name: 'Valuation', pillar: 'quant', scoringType: 'scored',
    score: 68, scoreBand: 'good', weight: 20,
    status: 'positive',
    interpretation: 'P/B of 2.1x vs sector average 2.5x — reasonably priced for the quality. P/E of 14x is fair.',
    quickInsight: 'Fair value — P/B 2.1x',
    metrics: [],
  },
  {
    id: 'financial_health', name: 'Financial Health', pillar: 'quant', scoringType: 'scored',
    score: 75, scoreBand: 'good', weight: 25,
    status: 'positive',
    interpretation: 'CAR at 17.5% (well above regulatory 11.5%). GNPA at 1.8% — clean book. PCR at 78%.',
    quickInsight: 'Strong capital adequacy & clean asset quality',
    metrics: [],
  },
  {
    id: 'technical', name: 'Technical Indicators', pillar: 'quant', scoringType: 'scored',
    score: 60, scoreBand: 'good', weight: 10,
    status: 'neutral',
    interpretation: 'Trading near 200 DMA. RSI at 52 — neutral. Consolidation phase after recent rally.',
    quickInsight: 'Neutral — consolidating',
    metrics: [],
  },
  {
    id: 'performance', name: 'Performance', pillar: 'quant', scoringType: 'context',
    status: 'neutral',
    interpretation: '1Y return of 15%, roughly in line with Nifty Bank. Underperforming ICICI Bank but outperforming SBI.',
    quickInsight: 'In-line with banking peers',
    metrics: [],
  },
  {
    id: 'institutional_signals', name: 'Institutional / Market Signals', pillar: 'quant', scoringType: 'context',
    status: 'positive',
    interpretation: 'FII holding at 48% — one of the highest in banking. 15 of 20 analysts rate BUY with avg target 15% upside.',
    quickInsight: 'High FII confidence + analyst BUY consensus',
    metrics: [],
  },
]

const axisBankQualFactors: SegmentVerdictV2[] = [
  {
    id: 'management_governance', name: 'Management & Governance', pillar: 'qual',
    scoringType: 'scored', score: 75, scoreBand: 'good', label: 'ADEQUATE', weight: 20,
    status: 'positive',
    interpretation: 'Professional management (no promoter). Strong board with independent oversight. Amitabh Chaudhry has delivered well since 2019.',
    confidenceIndicator: buildConfidence(14, 15),
    signalGroups: [
      {
        id: 'A', name: 'Promoter Alignment', role: 'anchor', score: 70,
        signals: [
          buildSignal('A1', 'Promoter Skin in the Game', 'A', 'hard', 60, 'monitor', 'No promoter — professionally managed bank. Alignment comes through ESOP and board oversight.'),
          buildSignal('A2', 'Holding Trend (3Y)', 'A', 'score_only', 65, 'monitor', 'No promoter holding to track. FII and DII holdings have been stable.'),
          buildSignal('A3', 'Pledge Status', 'A', 'soft', 95, 'strong', 'No promoter pledge — not applicable for professionally managed banks.'),
          buildSignal('A4', 'Insider Transactions', 'A', 'score_only', 70, 'strong', 'MD and senior management have exercised ESOPs and retained shares — positive signal.'),
          buildSignal('A5', 'Related Party Transactions', 'A', 'soft', 60, 'monitor', 'Standard related party transactions within banking norms — all at arm\'s length.'),
        ],
      },
      {
        id: 'B', name: 'Governance Structure', role: 'scored', weight: 0.50, score: 82,
        signals: [
          buildSignal('B1', 'Auditor Quality & Tenure', 'B', 'hard', 90, 'strong', 'S.R. Batliboi (EY affiliate) — top-tier auditor with clean reports.'),
          buildSignal('B2', 'Board Independence', 'B', 'score_only', 85, 'strong', 'Strong independent board with experienced banking and finance professionals. RBI-compliant governance.'),
          buildSignal('B3', 'Regulatory Compliance', 'B', 'hard', 75, 'strong', 'Minor RBI observations in the past but no material penalties. Compliance has improved significantly.'),
          buildSignal('B4', 'Compensation Alignment', 'B', 'score_only', 78, 'strong', 'RBI-approved compensation structure with clawback provisions. Performance-linked bonuses.'),
          buildSignal('B5', 'Disclosure Quality', 'B', 'score_only', 80, 'strong', 'Excellent disclosure quality — detailed segment reporting, proactive investor communication.'),
          buildSignal('B6', 'Whistleblower / Ethics', 'B', 'score_only', 82, 'strong', 'Robust ethics and compliance framework — RBI-mandated vigilance officer, anonymous reporting channels.'),
        ],
      },
      {
        id: 'C', name: 'Management Capability', role: 'scored', weight: 0.50, score: 75,
        signals: [
          buildSignal('C1', 'Capital Allocation Track Record', 'C', 'score_only', 72, 'strong', 'Citibank portfolio acquisition was well-executed. Organic growth is well-managed.'),
          buildSignal('C2', 'Execution vs Guidance', 'C', 'score_only', 78, 'strong', 'Management has delivered on NPA reduction, ROE improvement, and growth guidance.'),
          buildSignal('C3', 'Strategic Clarity', 'C', 'score_only', 75, 'strong', 'Clear strategy: grow retail, improve digital, reduce corporate concentration. GPS (Growth, Profitability, Sustainability) framework.'),
        ],
      },
    ],
  },
  {
    id: 'business_quality', name: 'Business Quality', pillar: 'qual',
    scoringType: 'scored', score: 72, scoreBand: 'good', label: 'GOOD', weight: 25,
    status: 'positive',
    interpretation: 'Improving retail mix strengthens business quality. NIM stability shows franchise strength. Well-diversified revenue streams.',
    confidenceIndicator: buildConfidence(11, 11),
    signalGroups: [
      { id: 'A', name: 'Margin & Return Durability', role: 'anchor', score: 72, signals: [
        buildSignal('A1', 'ROCE Consistency', 'A', 'score_only', 75, 'strong', 'Consistently improving ROCE — from 12% to 16% over 3 years.'),
        buildSignal('A2', 'Operating Margin Stability', 'A', 'score_only', 70, 'strong', 'NIM stable at 4.0-4.2% — demonstrates franchise pricing power.'),
        buildSignal('A3', 'Margin Expansion Trend', 'A', 'score_only', 65, 'strong', 'Gradual NIM expansion with improving cost-to-income ratio.'),
        buildSignal('A4', 'Revenue Quality', 'A', 'score_only', 78, 'strong', 'Good mix of interest income and fee income. Retail lending provides recurring revenue.'),
        buildSignal('A5', 'Return vs Cost of Capital', 'A', 'score_only', 72, 'strong', 'ROE of 16% comfortably exceeds cost of equity (~12%).'),
      ]},
      { id: 'B', name: 'Revenue Fragility', role: 'red_flag_only', score: 75, signals: [
        buildSignal('B1', 'Customer Concentration', 'B', 'soft', 80, 'strong', 'Diversified across millions of retail and corporate customers.'),
        buildSignal('B2', 'Geographic Concentration', 'B', 'soft', 65, 'strong', 'Pan-India presence with some western/northern skew.'),
        buildSignal('B3', 'Product/Service Concentration', 'B', 'soft', 78, 'strong', 'Diversified: retail loans, corporate banking, wealth management, insurance distribution.'),
      ]},
      { id: 'C', name: 'Pricing Power', role: 'scored', weight: 0.50, score: 68, signals: [
        buildSignal('C1', 'Pricing Power Evidence', 'C', 'score_only', 68, 'strong', 'Reasonable pricing power on retail products. Corporate lending is competitive.'),
      ]},
      { id: 'D', name: 'Earnings Backing', role: 'scored', weight: 0.50, score: 72, signals: [
        buildSignal('D1', 'Cash Backing of Earnings', 'D', 'score_only', 75, 'strong', 'Banking earnings are inherently cash-backed. Strong NII-to-PAT ratio.'),
        buildSignal('D2', 'Accrual Ratio', 'D', 'score_only', 68, 'strong', 'Low accrual ratio — provisions are conservative, earnings are largely real.'),
      ]},
    ],
  },
  {
    id: 'capital_discipline', name: 'Capital Discipline', pillar: 'qual',
    scoringType: 'scored', score: 70, scoreBand: 'good', label: 'GOOD', weight: 20,
    status: 'positive',
    interpretation: 'Good capital management with adequate CAR. Dividend payout is improving. No aggressive dilution.',
    confidenceIndicator: buildConfidence(14, 16),
    signalGroups: [
      { id: 'A', name: 'Dilution & Funding', role: 'scored', weight: 0.30, score: 72, signals: [
        buildSignal('A1', 'Equity Dilution History', 'A', 'score_only', 65, 'strong', 'Moderate dilution from capital raises — necessary for banking growth but well-managed.'),
        buildSignal('A2', 'Debt Management', 'A', 'score_only', 75, 'strong', 'As a bank, leverage is the business. CAR at 17.5% shows conservative capital management.'),
        buildSignal('A3', 'Funding Mix', 'A', 'score_only', 78, 'strong', 'Good CASA ratio at 45% — low-cost funding advantage.'),
        buildSignal('A4', 'Working Capital Efficiency', 'A', 'score_only', 70, 'strong', 'Efficient treasury management with good ALM practices.'),
      ]},
      { id: 'B', name: 'Capital Deployment', role: 'scored', weight: 0.45, score: 68, signals: [
        buildSignal('B1', 'Capex ROI', 'B', 'score_only', 65, 'strong', 'Branch expansion and digital investments showing returns.'),
        buildSignal('B2', 'R&D Effectiveness', 'B', 'score_only', 70, 'strong', 'Digital banking investments are reducing cost-to-income ratio.'),
        buildSignal('B3', 'Growth vs Maintenance Capex', 'B', 'score_only', 68, 'strong', 'Good balance between digital growth investments and branch network maintenance.'),
        buildSignal('B4', 'Investment Timing', 'B', 'score_only', 72, 'strong', 'Citibank acquisition timed well. Organic growth investments are steady.'),
        buildSignal('B5', 'Subsidiary Health', 'B', 'score_only', 65, 'strong', 'Axis AMC and Axis Securities are profitable. Max Life Insurance JV is value-accretive.'),
        buildSignal('B6', 'Capital Allocation Consistency', 'B', 'score_only', 70, 'strong', 'Consistent strategic direction under current management.'),
      ]},
      { id: 'C', name: 'Capital Returns', role: 'anchor', score: 68, signals: [
        buildSignal('C1', 'Dividend Track Record', 'C', 'score_only', 70, 'strong', 'Reinstated dividends and increasing payout. DPS growing at 20%+ CAGR.'),
        buildSignal('C2', 'Buyback Discipline', 'C', 'score_only', 50, 'monitor', 'No buybacks — banks typically don\'t buyback due to capital requirements.'),
        buildSignal('C3', 'Payout Sustainability', 'C', 'score_only', 75, 'strong', 'Payout ratio at 18% — sustainable and growing. Room to increase.'),
        buildSignal('C4', 'Total Shareholder Return', 'C', 'score_only', 72, 'strong', 'Decent TSR from dividend growth + price appreciation.'),
      ]},
      { id: 'D', name: 'Acquisition Track Record', role: 'scored', weight: 0.25, score: 72, signals: [
        buildSignal('D1', 'M&A Track Record', 'D', 'score_only', 72, 'strong', 'Citibank India consumer business acquisition well-integrated. Added 2.5M+ customers.'),
      ]},
    ],
  },
  {
    id: 'earnings_quality', name: 'Earnings Quality', pillar: 'qual',
    scoringType: 'scored', score: 74, scoreBand: 'good', label: 'GOOD', weight: 20,
    status: 'positive',
    interpretation: 'Clean earnings quality. Provisions are conservative. Minimal reporting concerns.',
    confidenceIndicator: buildConfidence(14, 14),
    signalGroups: [
      { id: 'A', name: 'Cash Conversion', role: 'anchor', score: 75, signals: [
        buildSignal('A1', 'OCF to PAT Ratio', 'A', 'score_only', 78, 'strong', 'Banking PAT is inherently cash-backed. Strong NII generation.'),
        buildSignal('A2', 'FCF Yield', 'A', 'score_only', 70, 'strong', 'Adequate free cash flow for a growth-stage bank.'),
        buildSignal('A3', 'Cash Conversion Cycle', 'A', 'score_only', 75, 'strong', 'Banking model has short CCC — deposits in, loans out.'),
      ]},
      { id: 'B', name: 'Balance Sheet Quality', role: 'scored', weight: 0.60, score: 78, signals: [
        buildSignal('B1', 'Receivables Quality', 'B', 'score_only', 80, 'strong', 'GNPA at 1.8% — clean loan book with improving trends.'),
        buildSignal('B2', 'Inventory Health', 'B', 'score_only', 75, 'strong', 'N/A for banks. Loan book quality is the equivalent — well-managed.'),
        buildSignal('B3', 'Contingent Liabilities', 'B', 'soft', 70, 'strong', 'Standard banking contingent liabilities — guarantees, LC, forward contracts.'),
        buildSignal('B4', 'Goodwill & Intangibles', 'B', 'score_only', 80, 'strong', 'Low goodwill relative to total assets.'),
        buildSignal('B5', 'Off-Balance Sheet Items', 'B', 'soft', 72, 'strong', 'Standard banking off-balance sheet items — well-disclosed.'),
      ]},
      { id: 'C', name: 'Reporting Integrity', role: 'red_flag_only', score: 88, signals: [
        buildSignal('C1', 'Restatement History', 'C', 'soft', 85, 'strong', 'No material restatements.'),
        buildSignal('C2', 'Accounting Policy Changes', 'C', 'hard', 90, 'strong', 'Stable accounting policies — Ind-AS compliant.'),
        buildSignal('C3', 'Auditor Opinion', 'C', 'hard', 88, 'strong', 'Clean auditor opinion from EY affiliate.'),
      ]},
      { id: 'D', name: 'Pattern Anomalies', role: 'scored', weight: 0.40, score: 72, signals: [
        buildSignal('D1', 'Revenue Recognition', 'D', 'score_only', 75, 'strong', 'NII recognition follows standard banking norms.'),
        buildSignal('D2', 'Expense Timing', 'D', 'score_only', 70, 'strong', 'Provisioning is consistent and conservative.'),
        buildSignal('D3', 'Tax Rate Anomalies', 'D', 'score_only', 72, 'strong', 'Effective tax rate at 25% — stable and in line with statutory rate.'),
      ]},
    ],
  },
  {
    id: 'execution_quality', name: 'Execution Quality', pillar: 'qual',
    scoringType: 'scored', score: 72, scoreBand: 'good', label: 'GOOD', weight: 15,
    status: 'positive',
    interpretation: 'Solid execution under current management. NPA reduction and ROE improvement are on track.',
    confidenceIndicator: buildConfidence(6, 7),
    signalGroups: [
      { id: 'A', name: 'Financial Delivery', role: 'anchor', score: 74, signals: [
        buildSignal('A1', 'Revenue Growth vs Guidance', 'A', 'score_only', 72, 'strong', 'Loan growth broadly in line with guided 15-18% range.'),
        buildSignal('A2', 'Margin Delivery vs Guidance', 'A', 'score_only', 75, 'strong', 'NIM guidance of 4.0-4.2% consistently met.'),
        buildSignal('A3', 'Earnings Surprise Pattern', 'A', 'score_only', 70, 'strong', 'Slight positive surprises in recent quarters from lower credit costs.'),
        buildSignal('A4', 'Quarterly Consistency', 'A', 'score_only', 78, 'strong', 'Predictable quarterly results — smooth execution without surprises.'),
      ]},
      { id: 'B', name: 'Operational Delivery', role: 'scored', weight: 1.0, score: 70, signals: [
        buildSignal('B1', 'Operational KPI Achievement', 'B', 'score_only', 72, 'strong', 'CASA ratio, digital metrics, and cost-to-income targets are on track.'),
        buildSignal('B2', 'Market Share Trajectory', 'B', 'score_only', 68, 'strong', 'Gaining market share in retail lending. Digital acquisition improving.'),
      ]},
    ],
  },
]

// ============================================================
// TCS — IT Services / Blue Chip
// ============================================================

const tcsQuantSegments: SegmentVerdictV2[] = [
  {
    id: 'profitability', name: 'Profitability', pillar: 'quant', scoringType: 'scored',
    score: 88, scoreBand: 'strong', weight: 20,
    status: 'positive',
    interpretation: 'Industry-leading margins at 26%+ operating margin. ROE consistently above 40%. Cash-rich business.',
    quickInsight: 'Best-in-class margins — 26%+ OPM',
    metrics: [],
  },
  {
    id: 'growth', name: 'Growth', pillar: 'quant', scoringType: 'scored',
    score: 55, scoreBand: 'mixed', weight: 25,
    status: 'neutral',
    interpretation: 'Revenue growth of 8-10% in constant currency — steady but not exciting. Order book remains strong.',
    quickInsight: 'Steady but not exciting — 8-10% CC growth',
    metrics: [],
  },
  {
    id: 'valuation', name: 'Valuation', pillar: 'quant', scoringType: 'scored',
    score: 50, scoreBand: 'mixed', weight: 20,
    status: 'neutral',
    interpretation: 'P/E of 30x on FY25E — premium for quality but leaves limited upside. Trading above historical average.',
    quickInsight: 'Fair to expensive — P/E 30x',
    metrics: [],
  },
  {
    id: 'financial_health', name: 'Financial Health', pillar: 'quant', scoringType: 'scored',
    score: 92, scoreBand: 'strong', weight: 25,
    status: 'positive',
    interpretation: 'Zero debt, ₹45K Cr cash. Strong FCF generation. One of the most financially sound companies in India.',
    quickInsight: 'Fort Knox balance sheet — zero debt, ₹45K Cr cash',
    metrics: [],
  },
  {
    id: 'technical', name: 'Technical Indicators', pillar: 'quant', scoringType: 'scored',
    score: 52, scoreBand: 'mixed', weight: 10,
    status: 'neutral',
    interpretation: 'Range-bound between ₹3,800-4,200. RSI at 48 — neutral. Waiting for directional trigger.',
    quickInsight: 'Range-bound — waiting for trigger',
    metrics: [],
  },
  {
    id: 'performance', name: 'Performance', pillar: 'quant', scoringType: 'context',
    status: 'neutral',
    interpretation: '1Y return of 8%, underperforming Nifty. IT sector in a cautious phase due to macro uncertainty.',
    quickInsight: 'Underperforming market — sector headwinds',
    metrics: [],
  },
  {
    id: 'institutional_signals', name: 'Institutional / Market Signals', pillar: 'quant', scoringType: 'context',
    status: 'positive',
    interpretation: 'FII holding at 12% — stable. MF holding at 5%. 12 of 18 analysts rate BUY/HOLD. Seen as defensive quality play.',
    quickInsight: 'Defensive favorite — stable institutional interest',
    metrics: [],
  },
]

const tcsQualFactors: SegmentVerdictV2[] = [
  {
    id: 'management_governance', name: 'Management & Governance', pillar: 'qual',
    scoringType: 'scored', score: 85, scoreBand: 'strong', label: 'TRUSTED', weight: 20,
    status: 'positive',
    interpretation: 'Tata group governance is gold standard. K Krithivasan is an internal successor with deep domain expertise. Transparent and shareholder-friendly.',
    confidenceIndicator: buildConfidence(14, 15),
    signalGroups: [
      { id: 'A', name: 'Promoter Alignment', role: 'anchor', score: 88, signals: [
        buildSignal('A1', 'Promoter Skin in the Game', 'A', 'hard', 90, 'strong', 'Tata Sons holds 72% — enormous skin in the game. Tata brand is tied to TCS performance.'),
        buildSignal('A2', 'Holding Trend (3Y)', 'A', 'score_only', 88, 'strong', 'Tata Sons holding has been stable at 72% — no selling by promoter.'),
        buildSignal('A3', 'Pledge Status', 'A', 'soft', 95, 'strong', 'Zero promoter pledge — Tata group has never pledged TCS shares.'),
        buildSignal('A4', 'Insider Transactions', 'A', 'score_only', 80, 'strong', 'No material insider selling. Senior management retains ESOPs.'),
        buildSignal('A5', 'Related Party Transactions', 'A', 'soft', 82, 'strong', 'RPTs exist with other Tata companies but are well-disclosed, at arm\'s length, and small relative to revenue.'),
      ]},
      { id: 'B', name: 'Governance Structure', role: 'scored', weight: 0.50, score: 88, signals: [
        buildSignal('B1', 'Auditor Quality & Tenure', 'B', 'hard', 92, 'strong', 'Deloitte — top-tier global auditor with appropriate rotation.'),
        buildSignal('B2', 'Board Independence', 'B', 'score_only', 90, 'strong', 'Excellent board independence with global experts from technology and business.'),
        buildSignal('B3', 'Regulatory Compliance', 'B', 'hard', 92, 'strong', 'Spotless regulatory record — zero SEBI or stock exchange penalties.'),
        buildSignal('B4', 'Compensation Alignment', 'B', 'score_only', 82, 'strong', 'Tata ethos of moderation — CEO compensation is reasonable relative to company size.'),
        buildSignal('B5', 'Disclosure Quality', 'B', 'score_only', 88, 'strong', 'Gold-standard disclosures — detailed quarterly reports, proactive guidance.'),
        buildSignal('B6', 'Whistleblower / Ethics', 'B', 'score_only', 85, 'strong', 'Robust Tata Code of Conduct, anonymous ethics hotline, regular compliance audits.'),
      ]},
      { id: 'C', name: 'Management Capability', role: 'scored', weight: 0.50, score: 80, signals: [
        buildSignal('C1', 'Capital Allocation Track Record', 'C', 'score_only', 85, 'strong', 'Conservative and shareholder-friendly — high dividend + buybacks. Selective acquisitions.'),
        buildSignal('C2', 'Execution vs Guidance', 'C', 'score_only', 78, 'strong', 'Generally meets guidance. Occasional misses due to macro headwinds, not execution.'),
        buildSignal('C3', 'Strategic Clarity', 'C', 'score_only', 78, 'strong', 'Clear strategy: cloud, AI/GenAI, industry cloud solutions. Well-articulated technology bets.'),
      ]},
    ],
  },
  {
    id: 'business_quality', name: 'Business Quality', pillar: 'qual',
    scoringType: 'scored', score: 82, scoreBand: 'strong', label: 'STRONG', weight: 25,
    status: 'positive',
    interpretation: 'Best-in-class margins in IT services. Strong client relationships with 90%+ retention. Diversified revenue streams.',
    confidenceIndicator: buildConfidence(11, 11),
    signalGroups: [
      { id: 'A', name: 'Margin & Return Durability', role: 'anchor', score: 85, signals: [
        buildSignal('A1', 'ROCE Consistency', 'A', 'score_only', 90, 'strong', 'ROCE consistently above 50% — extraordinary capital efficiency.'),
        buildSignal('A2', 'Operating Margin Stability', 'A', 'score_only', 85, 'strong', 'Operating margins stable at 24-26% — industry-leading for IT services.'),
        buildSignal('A3', 'Margin Expansion Trend', 'A', 'score_only', 65, 'strong', 'Margins are stable rather than expanding — at peak efficiency already.'),
        buildSignal('A4', 'Revenue Quality', 'A', 'score_only', 92, 'strong', 'Long-term contracts with Fortune 500 clients — highly predictable revenue.'),
        buildSignal('A5', 'Return vs Cost of Capital', 'A', 'score_only', 90, 'strong', 'ROE of 45%+ vs cost of equity ~12% — massive value creation.'),
      ]},
      { id: 'B', name: 'Revenue Fragility', role: 'red_flag_only', score: 72, signals: [
        buildSignal('B1', 'Customer Concentration', 'B', 'soft', 68, 'strong', 'Top 5 clients are ~15% of revenue — diversified but BFSI sector is 32%.'),
        buildSignal('B2', 'Geographic Concentration', 'B', 'soft', 70, 'strong', 'US is 52% of revenue — significant but unavoidable for IT services.'),
        buildSignal('B3', 'Product/Service Concentration', 'B', 'soft', 78, 'strong', 'Diversified across consulting, application management, BPO, and infrastructure services.'),
      ]},
      { id: 'C', name: 'Pricing Power', role: 'scored', weight: 0.50, score: 75, signals: [
        buildSignal('C1', 'Pricing Power Evidence', 'C', 'score_only', 75, 'strong', 'Ability to pass on wage inflation to clients. Premium pricing for digital/cloud services.'),
      ]},
      { id: 'D', name: 'Earnings Backing', role: 'scored', weight: 0.50, score: 88, signals: [
        buildSignal('D1', 'Cash Backing of Earnings', 'D', 'score_only', 90, 'strong', 'Operating cash flow consistently exceeds PAT — earnings are highly cash-backed.'),
        buildSignal('D2', 'Accrual Ratio', 'D', 'score_only', 85, 'strong', 'Very low accrual ratio — TCS earnings are among the most trustworthy in India.'),
      ]},
    ],
  },
  {
    id: 'capital_discipline', name: 'Capital Discipline', pillar: 'qual',
    scoringType: 'scored', score: 88, scoreBand: 'strong', label: 'STRONG', weight: 20,
    status: 'positive',
    interpretation: 'Best-in-class capital returns — consistent dividends + buybacks. Minimal dilution. Conservative balance sheet.',
    confidenceIndicator: buildConfidence(15, 16),
    signalGroups: [
      { id: 'A', name: 'Dilution & Funding', role: 'scored', weight: 0.30, score: 90, signals: [
        buildSignal('A1', 'Equity Dilution History', 'A', 'score_only', 85, 'strong', 'Share count has declined through buybacks — shareholder-friendly capital management.'),
        buildSignal('A2', 'Debt Management', 'A', 'score_only', 95, 'strong', 'Zero debt — entirely self-funded from operations.'),
        buildSignal('A3', 'Funding Mix', 'A', 'score_only', 92, 'strong', 'Entirely internally funded — no external capital needed.'),
        buildSignal('A4', 'Working Capital Efficiency', 'A', 'score_only', 85, 'strong', 'Efficient working capital management with DSO of ~70 days — industry average.'),
      ]},
      { id: 'B', name: 'Capital Deployment', role: 'scored', weight: 0.45, score: 80, signals: [
        buildSignal('B1', 'Capex ROI', 'B', 'score_only', 82, 'strong', 'Capex is minimal — asset-light business. Investments in training and technology deliver returns.'),
        buildSignal('B2', 'R&D Effectiveness', 'B', 'score_only', 78, 'strong', 'R&D investments in AI, cloud, and industry platforms are translating to deal wins.'),
        buildSignal('B3', 'Growth vs Maintenance Capex', 'B', 'score_only', 80, 'strong', 'Mostly growth-oriented — new delivery centers, technology platforms.'),
        buildSignal('B4', 'Investment Timing', 'B', 'score_only', 75, 'strong', 'Steady, consistent investment pace — not cyclical.'),
        buildSignal('B5', 'Subsidiary Health', 'B', 'score_only', 82, 'strong', 'TCS BaNCS, Diligenta, and other subsidiaries are profitable and strategic.'),
        buildSignal('B6', 'Capital Allocation Consistency', 'B', 'score_only', 85, 'strong', 'Very consistent capital allocation — dividends, buybacks, minimal M&A. Predictable.'),
      ]},
      { id: 'C', name: 'Capital Returns', role: 'anchor', score: 90, signals: [
        buildSignal('C1', 'Dividend Track Record', 'C', 'score_only', 92, 'strong', 'Consistent dividend growth — special dividends in addition to regular. Total payout ~80% of FCF.'),
        buildSignal('C2', 'Buyback Discipline', 'C', 'score_only', 88, 'strong', 'Regular buybacks at reasonable valuations — ₹18,000 Cr in FY24.'),
        buildSignal('C3', 'Payout Sustainability', 'C', 'score_only', 90, 'strong', 'Total payout ratio of ~80% is sustainable given ₹45K Cr cash and strong FCF.'),
        buildSignal('C4', 'Total Shareholder Return', 'C', 'score_only', 88, 'strong', 'Excellent TSR: dividends + buybacks + modest appreciation. Shareholder-friendly culture.'),
      ]},
      { id: 'D', name: 'Acquisition Track Record', role: 'scored', weight: 0.25, score: 78, signals: [
        buildSignal('D1', 'M&A Track Record', 'D', 'score_only', 78, 'strong', 'Selective, small acquisitions — TCS prefers organic growth. Acquisitions are well-integrated.'),
      ]},
    ],
  },
  {
    id: 'earnings_quality', name: 'Earnings Quality', pillar: 'qual',
    scoringType: 'scored', score: 90, scoreBand: 'strong', label: 'STRONG', weight: 20,
    status: 'positive',
    interpretation: 'Gold-standard earnings quality. OCF consistently exceeds PAT. Conservative provisions. Clean audits.',
    confidenceIndicator: buildConfidence(14, 14),
    signalGroups: [
      { id: 'A', name: 'Cash Conversion', role: 'anchor', score: 90, signals: [
        buildSignal('A1', 'OCF to PAT Ratio', 'A', 'score_only', 92, 'strong', 'OCF is 110-120% of PAT — earnings are more than fully cash-backed.'),
        buildSignal('A2', 'FCF Yield', 'A', 'score_only', 85, 'strong', 'Strong FCF yield of 3.5% — good for a quality compounder.'),
        buildSignal('A3', 'Cash Conversion Cycle', 'A', 'score_only', 80, 'strong', 'Cash conversion cycle of ~70 days — efficient for IT services.'),
      ]},
      { id: 'B', name: 'Balance Sheet Quality', role: 'scored', weight: 0.60, score: 92, signals: [
        buildSignal('B1', 'Receivables Quality', 'B', 'score_only', 85, 'strong', 'Receivables are well-managed with ~70 day DSO. Fortune 500 clients = low default risk.'),
        buildSignal('B2', 'Inventory Health', 'B', 'score_only', 90, 'strong', 'N/A — services company. Unbilled revenue is well-managed.'),
        buildSignal('B3', 'Contingent Liabilities', 'B', 'soft', 88, 'strong', 'Minimal contingent liabilities — clean corporate structure.'),
        buildSignal('B4', 'Goodwill & Intangibles', 'B', 'score_only', 92, 'strong', 'Very low goodwill — TCS grows organically, not through acquisitions.'),
        buildSignal('B5', 'Off-Balance Sheet Items', 'B', 'soft', 90, 'strong', 'Minimal off-balance sheet items — transparent structure.'),
      ]},
      { id: 'C', name: 'Reporting Integrity', role: 'red_flag_only', score: 95, signals: [
        buildSignal('C1', 'Restatement History', 'C', 'soft', 95, 'strong', 'Zero restatements — pristine reporting history.'),
        buildSignal('C2', 'Accounting Policy Changes', 'C', 'hard', 95, 'strong', 'Rock-solid accounting policies — no changes to flatter results.'),
        buildSignal('C3', 'Auditor Opinion', 'C', 'hard', 95, 'strong', 'Clean Deloitte opinion every year — no qualifications or emphasis of matter.'),
      ]},
      { id: 'D', name: 'Pattern Anomalies', role: 'scored', weight: 0.40, score: 82, signals: [
        buildSignal('D1', 'Revenue Recognition', 'D', 'score_only', 85, 'strong', 'Revenue recognition follows predictable quarterly patterns — no unusual spikes.'),
        buildSignal('D2', 'Expense Timing', 'D', 'score_only', 80, 'strong', 'Consistent expense recognition across quarters.'),
        buildSignal('D3', 'Tax Rate Anomalies', 'D', 'score_only', 82, 'strong', 'Effective tax rate at 25-26% — stable and in line with statutory rate.'),
      ]},
    ],
  },
  {
    id: 'execution_quality', name: 'Execution Quality', pillar: 'qual',
    scoringType: 'scored', score: 75, scoreBand: 'good', label: 'GOOD', weight: 15,
    status: 'positive',
    interpretation: 'Consistent execution against guidance. Market share stable. AI/GenAI deals are translating to revenue.',
    confidenceIndicator: buildConfidence(6, 7),
    signalGroups: [
      { id: 'A', name: 'Financial Delivery', role: 'anchor', score: 76, signals: [
        buildSignal('A1', 'Revenue Growth vs Guidance', 'A', 'score_only', 72, 'strong', 'Generally meets CC growth guidance of 8-10%. Macro headwinds occasionally cause slight misses.'),
        buildSignal('A2', 'Margin Delivery vs Guidance', 'A', 'score_only', 80, 'strong', 'Margin guidance consistently met — demonstrates strong operational discipline.'),
        buildSignal('A3', 'Earnings Surprise Pattern', 'A', 'score_only', 72, 'strong', 'Earnings roughly in line with consensus — TCS is predictable.'),
        buildSignal('A4', 'Quarterly Consistency', 'A', 'score_only', 80, 'strong', 'Very predictable quarterly results. Seasonal pattern (Q1 strong, Q3 weak) is well-understood.'),
      ]},
      { id: 'B', name: 'Operational Delivery', role: 'scored', weight: 1.0, score: 72, signals: [
        buildSignal('B1', 'Operational KPI Achievement', 'B', 'score_only', 75, 'strong', 'Attrition declining, utilization stable, deal wins strong — operational KPIs on track.'),
        buildSignal('B2', 'Market Share Trajectory', 'B', 'score_only', 70, 'strong', 'Market share stable — maintaining #1 position in Indian IT. Not gaining significantly.'),
      ]},
    ],
  },
]

// ============================================================
// BUILD STOCK VERDICT V2
// ============================================================

function buildPillarVerdict(
  pillar: 'quant' | 'qual' | 'risk',
  name: string,
  segments: SegmentVerdictV2[]
): PillarVerdict {
  // Compute weighted score from scored segments
  const scoredSegments = segments.filter(s => s.scoringType === 'scored' && s.score !== undefined)
  const totalWeight = scoredSegments.reduce((sum, s) => sum + (s.weight || 0), 0)
  const weightedScore = totalWeight > 0
    ? Math.round(scoredSegments.reduce((sum, s) => sum + (s.score! * (s.weight || 0)), 0) / totalWeight)
    : 0

  const scoreBand = getScoreBandEnum(weightedScore)

  const labels: Record<string, string> = {
    strong: 'STRONG', good: 'GOOD', mixed: 'MIXED', weak: 'WEAK', suppressed: 'SUPPRESSED',
  }

  return {
    pillar,
    name,
    score: weightedScore,
    scoreBand,
    label: labels[scoreBand],
    summary: `${name} analysis based on ${segments.length} segments`,
    segments,
  }
}

function buildStockVerdictV2(
  stockId: string,
  stockName: string,
  ticker: string,
  sector: string,
  quantSegments: SegmentVerdictV2[],
  qualFactors: SegmentVerdictV2[],
  newsEvents: NewsEvent[],
  profileId: string,
): StockVerdictV2 {
  const quantPillar = buildPillarVerdict('quant', 'Quantitative Analysis', quantSegments)
  const qualPillar = buildPillarVerdict('qual', 'Qualitative Analysis', qualFactors)

  // Risk pillar (aggregated from red flags across both pillars)
  const allRedFlags = [...quantSegments, ...qualFactors]
    .flatMap(s => s.redFlags || [])
  const riskScore = allRedFlags.length === 0 ? 80 : Math.max(20, 80 - allRedFlags.length * 15)
  const riskPillar: PillarVerdict = {
    pillar: 'risk',
    name: 'Risk Assessment',
    score: riskScore,
    scoreBand: getScoreBandEnum(riskScore),
    label: riskScore >= 80 ? 'LOW RISK' : riskScore >= 60 ? 'MODERATE' : 'ELEVATED',
    summary: allRedFlags.length === 0
      ? 'No red flags detected across analysis'
      : `${allRedFlags.length} risk factor(s) identified`,
    segments: [],
  }

  // Overall score — independent weighted computation
  // Simple weighted average for mock: Quant 50% + Qual 30% + Risk 20%
  const overallScore = Math.round(
    quantPillar.score * 0.50 + qualPillar.score * 0.30 + riskPillar.score * 0.20
  )
  const overall = getOverallVerdict(overallScore)

  return {
    overallVerdict: overall.verdict,
    overallScore,
    overallLabel: overall.label,
    overallSummary: `${stockName} scores ${overallScore}/100 — ${overall.label}`,
    pillars: [quantPillar, qualPillar, riskPillar],
    newsEvents,
    ticker,
    stockName,
    sector,
    lastUpdated: '2025-01-15',
    stockId,
    profileId,
    peerRank: 1,
    peerTotal: 5,
    topSignals: [],
    topConcerns: [],
    verdictRationale: `Based on comprehensive Quant (${quantPillar.score}/100) + Qual (${qualPillar.score}/100) + Risk (${riskPillar.score}/100) analysis.`,
    positionSizing: 'See detailed analysis',
    entryGuidance: 'See detailed analysis',
  }
}

// ============================================================
// MOCK NEWS EVENTS
// ============================================================

const zomatoNewsEvents: NewsEvent[] = [
  { id: 'z-n1', type: 'quarterly_results', bucket: 'financial_performance', title: 'Q2 FY25: First profitable quarter — PAT ₹176 Cr', source: 'BSE Filing', date: '2025-01-10', severity: 'positive', investorMeaning: 'Profitability milestone achieved — validates unit economics at scale.', impactPillars: ['quant', 'qual'] },
  { id: 'z-n2', type: 'concall_highlights', bucket: 'financial_performance', title: 'Concall: Blinkit dark stores to reach 1,000 by FY26', source: 'Investor Relations', date: '2025-01-12', severity: 'positive', investorMeaning: 'Aggressive expansion indicates management confidence in quick commerce TAM.', impactPillars: ['quant'] },
  { id: 'z-n3', type: 'block_deal', bucket: 'corporate_actions', title: 'FII block deal: 2M shares purchased at ₹265', source: 'NSE Bulk Deals', date: '2025-01-08', severity: 'positive', investorMeaning: 'Large institutional buying signals confidence at current valuations.', impactPillars: ['quant'] },
  { id: 'z-n4', type: 'index_inclusion', bucket: 'market_signals', title: 'Included in MSCI India Index', source: 'MSCI', date: '2024-11-25', severity: 'positive', investorMeaning: 'Index inclusion brings passive fund inflows and validates market-cap maturity.', impactPillars: ['quant'] },
  { id: 'z-n5', type: 'broker_upgrade', bucket: 'sentiment_third_party', title: 'Goldman Sachs upgrades to BUY, target ₹320', source: 'Goldman Sachs Research', date: '2025-01-05', severity: 'positive', investorMeaning: 'Major analyst upgrade signals institutional view shift on growth sustainability.', impactPillars: ['quant'] },
]

const axisBankNewsEvents: NewsEvent[] = [
  { id: 'ab-n1', type: 'quarterly_results', bucket: 'financial_performance', title: 'Q3 FY25: PAT up 18% YoY to ₹6,071 Cr', source: 'BSE Filing', date: '2025-01-15', severity: 'positive', investorMeaning: 'Strong earnings growth driven by lower credit costs and retail loan growth.', impactPillars: ['quant'] },
  { id: 'ab-n2', type: 'dividend', bucket: 'financial_performance', title: 'Interim dividend of ₹1/share declared', source: 'BSE Filing', date: '2025-01-15', severity: 'positive', investorMeaning: 'Growing dividend signals management confidence in sustained earnings.', impactPillars: ['qual'] },
  { id: 'ab-n3', type: 'credit_rating', bucket: 'financial_performance', title: 'CRISIL reaffirms AAA rating with stable outlook', source: 'CRISIL', date: '2024-12-10', severity: 'positive', investorMeaning: 'Highest credit quality maintained — strong institutional confidence.', impactPillars: ['quant', 'qual'] },
  { id: 'ab-n4', type: 'regulatory_action', bucket: 'governance_ownership', title: 'RBI: No adverse observations in annual inspection', source: 'RBI', date: '2024-11-30', severity: 'positive', investorMeaning: 'Clean regulatory track record signals sound governance.', impactPillars: ['qual'] },
  { id: 'ab-n5', type: 'partnership', bucket: 'strategic_business', title: 'Axis-Max Life integration completed ahead of schedule', source: 'Press Release', date: '2024-12-20', severity: 'positive', investorMeaning: 'Successful integration expands bancassurance revenue and cross-sell potential.', impactPillars: ['qual'] },
]

const tcsNewsEvents: NewsEvent[] = [
  { id: 'tcs-n1', type: 'quarterly_results', bucket: 'financial_performance', title: 'Q3 FY25: Revenue up 6% YoY CC, margins at 26.1%', source: 'BSE Filing', date: '2025-01-09', severity: 'neutral', investorMeaning: 'In-line results — growth is steady but not accelerating. Margins resilient.', impactPillars: ['quant'] },
  { id: 'tcs-n2', type: 'buyback', bucket: 'corporate_actions', title: '₹18,000 Cr buyback at ₹4,150/share completed', source: 'BSE Filing', date: '2024-12-15', severity: 'positive', investorMeaning: 'Continues shareholder-friendly capital return. Reduces share count ~1%.', impactPillars: ['qual'] },
  { id: 'tcs-n3', type: 'deal_win', bucket: 'strategic_business', title: 'Wins $2B multi-year deal with UK financial services firm', source: 'Press Release', date: '2025-01-05', severity: 'positive', investorMeaning: 'Large deal win validates competitive position and provides revenue visibility.', impactPillars: ['quant'] },
  { id: 'tcs-n4', type: 'sector_event', bucket: 'external_macro', title: 'US Fed signals slower rate cuts — IT demand impact uncertain', source: 'Bloomberg', date: '2025-01-08', severity: 'watch', investorMeaning: 'Higher-for-longer rates may delay enterprise IT spending decisions.', impactPillars: ['quant'] },
  { id: 'tcs-n5', type: 'annual_report', bucket: 'documents_reference', title: 'Integrated Annual Report FY24 released', source: 'TCS Investor Relations', date: '2024-07-15', severity: 'neutral', investorMeaning: 'Comprehensive disclosure of strategy, ESG commitments, and financial outlook.', impactPillars: ['qual'] },
]

// ============================================================
// EXPORTED VERDICTS
// ============================================================

export const verdictsV2: StockVerdictV2[] = [
  // Zomato
  buildStockVerdictV2('zomato', 'Zomato (Eternal)', 'ZOMATO', 'New Economy / Food Tech', zomatoQuantSegments, zomatoQualFactors, zomatoNewsEvents, 'ankit'),

  // Axis Bank
  buildStockVerdictV2('axisbank', 'Axis Bank', 'AXISBANK', 'Banking / Financial Services', axisBankQuantSegments, axisBankQualFactors, axisBankNewsEvents, 'ankit'),

  // TCS
  buildStockVerdictV2('tcs', 'Tata Consultancy Services', 'TCS', 'IT Services', tcsQuantSegments, tcsQualFactors, tcsNewsEvents, 'ankit'),
]

/**
 * Get V2 verdict for a stock
 */
export function getVerdictV2(stockId: string): StockVerdictV2 | undefined {
  return verdictsV2.find(v => v.stockId === stockId)
}

/**
 * Get all V2 verdicts
 */
export function getAllVerdictsV2(): StockVerdictV2[] {
  return verdictsV2
}
